//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/02/2025 10:54:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class Alienlist {

        public Alienlist()
        {
            this.Healthchecks = new List<Healthcheck>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.StringLength(13)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Alcode { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int EmpID { get; set; }

        public virtual string Reqcode { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string Alpassport { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string AltypeID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string AlprefixID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string Alprefixen { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string Alnameen { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string Alsnameen { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public virtual string Albdate { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string AlgenderID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(1)]
        public virtual string AlnationID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public virtual string AlposID { get; set; }

        public virtual string Alcity { get; set; }

        public virtual string Alcountry { get; set; }

        public virtual string Aladdress { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool IsActive { get; set; }

        public virtual Alpo Alpo { get; set; }

        public virtual Alprefix Alprefix { get; set; }

        public virtual Alnation Alnation { get; set; }

        public virtual Algender Algender { get; set; }

        public virtual Employee Employee { get; set; }

        public virtual IList<Healthcheck> Healthchecks { get; set; }

        public virtual Altype Altype { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
