//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/02/2025 10:54:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class Employee {

        public Employee()
        {
            this.Alienlists = new List<Alienlist>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int EmpID { get; set; }

        public virtual string EmpName { get; set; }

        public virtual string Wkaddress { get; set; }

        public virtual string Btname { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool IsActive { get; set; }

        public virtual IList<Alienlist> Alienlists { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
