//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/25/2025 9:16:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class Healthcheck {

        public Healthcheck()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int HealthID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(13)]
        public virtual string Alcode { get; set; }

        public virtual string Alchkhos { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public virtual string AlchkstatusID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public virtual string Alchkdate { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(2)]
        public virtual string Alchkprovid { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string Licenseno { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string Chkname { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string Chkposition { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Alchkdesc { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(500)]
        public virtual string Alchkdoc { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool IsActive { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int UserIDManage { get; set; }

        public virtual Alienlist Alienlist { get; set; }

        public virtual Province Province { get; set; }

        public virtual User User { get; set; }

        public virtual Alchkstatu Alchkstatu { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
