//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 2/25/2025 9:16:01 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class HistoryHealth {

        public HistoryHealth()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int HistoryHealthID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(13)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Alcode { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        public virtual string Alnameen { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public virtual string Alchkdate { get; set; }

        public virtual DateTime? UploadDate { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int UserIDManage { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
