//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/02/2025 10:54:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class Hospital {

        public Hospital()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int HospitalID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string HospitalName { get; set; }

        public virtual string HospitalAddress { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdateAt { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool IsActive { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
