//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/02/2025 10:54:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class Permission {

        public Permission()
        {
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int PermissionsID { get; set; }

        public virtual int? UserID { get; set; }

        public virtual int? MenuID { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool CanView { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool CanCreate { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool CanUpdate { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool CanDelete { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        public virtual Menu Menu { get; set; }

        public virtual User User { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
