//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Entity Developer tool using EF Core template.
// Code is generated on: 26/02/2025 10:54:53
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Linq.Expressions;

namespace HealthCheck.Models
{
    public partial class User {

        public User()
        {
            this.Permissions = new List<Permission>();
            this.Healthchecks = new List<Healthcheck>();
            this.LogSystems = new List<LogSystem>();
            OnCreated();
        }

        [System.ComponentModel.DataAnnotations.Key]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual int UserID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(13)]
        public virtual string CardID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(50)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string Username { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        [System.ComponentModel.DataAnnotations.Required()]
        public virtual string PasswordHash { get; set; }

        public virtual int? PositionID { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(255)]
        public virtual string Email { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(10)]
        public virtual string Phone { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string FirstName { get; set; }

        [System.ComponentModel.DataAnnotations.StringLength(100)]
        public virtual string LastName { get; set; }

        public virtual string ImagesPath { get; set; }

        public virtual DateTime? CreatedAt { get; set; }

        public virtual DateTime? UpdatedAt { get; set; }

        [System.ComponentModel.DataAnnotations.Required()]
        public virtual bool IsActive { get; set; }

        public virtual Position Position { get; set; }

        public virtual IList<Permission> Permissions { get; set; }

        public virtual IList<Healthcheck> Healthchecks { get; set; }

        public virtual IList<LogSystem> LogSystems { get; set; }

        #region Extensibility Method Definitions

        partial void OnCreated();

        #endregion
    }

}
